package com.valenpateltimesetu.ui.quotes
val splashQuotes = listOf(
    "Focus. Break. Repeat.⏳",
    "25 minutes to greatness. 🌟",
    "Small sprints, big results.🚀",
    "Your time, your rules.⌛",
    "Stay sharp, one Pomodoro at a time. 🍅",
    "Chop your tasks like tomatoes! 🍅🔪",
    "Tick-tock, let’s rock!🎸",
    "Slice your time. Savor your success.🥇",
    "From tomato to tornado—stay productive!🌪️",
    "Break your work, not your brain.💡",
    "Every Pomodoro is a step closer to your dreams.🍅",
    "Time is your most precious ingredient.💎",
    "Work smart, rest well, repeat daily. 🛠️",
    "Discipline is built in 25-minute bursts.💪",
    "Turn minutes into milestones.🏆",
    "Make every tick count.✅",
    "Your focus, freshly served. 🍽️",
    "Pomodoro: the art of productive pause.🎨",
    "Work in bursts, win in life.🏆",
    "Tomato-powered productivity. ⚡",
    "Conquer your to-do list in slices.📝",
    "Where minutes meet mastery.🎯",
    "Pause, refresh, crush it again.🔄",
    "Time-chopping for champions.🕒",
    "Pomodoro: small bites, big goals.🍅",
    "Sprint, rest, repeat to success.🏃‍♂️",
    "25 minutes closer to your best self.🌟️",
    "One Pomodoro at a time, all day long.🍅🕒",
    "Cook your goals with tomato timing.🍳",
    "Rest isn’t wasted—it’s fuel for focus.💤"
)
